---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quangtd.com
spec:
  rules:
  - host: quangtd.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    service: tomcat-service
spec:
  selector:
    service: tomcat
  type: NodePort
  ports:
  - port: 9000
    targetPort: 8080
    nodePort: 30337
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
spec:
  selector:
    matchLabels:
      service: tomcat
  replicas: 3
  template:
    metadata:
      labels:
        service: tomcat
    spec:
      containers:
      - name: tomcat
        image: quangtran1701/tomcat-sample:v2.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 300m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 100Mi
        ports:
        - containerPort: 8080